server:
  port: ${FINANCE_CORE_PORT:8081}

spring:
  application:
    name: finance-core

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
